### ISSUE TITLE
about npm install

### ISSUE THREAD

**Issue by seizedsupremacy** [Askwrite/node-csgo-reportbot#10]
Hey, I really appreciate the work youve done here. Unfortunately I'm already failing at installing the dependencies. I do have read the readme, and did some research about npm install on google, however I couldn't really figure out what I am doing wrong. I installed node.js, and tried `npm install /directory/` on cmd. What am I missing here? Thanks. 

Edit: Okay, got it to work, installed everything correctly, and ran the updater using `node protos/updater.js`.
created and filled accounts.txt, however the bot only works until: 

> [STEAM CLIENT - xyz] Logged in!
[GC - xyz] Client Hello sent!
> 

Steamguard is disabled as well. Any solutions?

**Comment by Askwrite** [comment]
You have to wait till he received the "welcome" from the csgo client. Try with another account

**Comment by seizedsupremacy** [comment]
Thanks for the answer. You're right, I forgot that I removed CSGO from that first account on the list. I've restored it now. everything working flawlessly. Thanks for your help
last question: how many accounts are needed for this to work ? will 6 be enough?

**Comment by Askwrite** [comment]
I think 11 :)
