### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by makikg123** [Askwrite/node-csgo-reportbot#16]
Hi, i get failed to login all the time, i have removed Steamguard from the accounts what am i doing wrong? Renamed to accounts.txt and username:password .. anyone know?

**Comment by makikg123** [comment]
Close problem solved, cant read letters that are like äöå

**Comment by 0815ACC** [comment]
@Galenika could you please tell me how I can contact you?
I would like to ask you to remove a repository you forked for privacy reasons.
You can also send me a mail to atpxpta@web.de if you don't want to write anything here
