### ISSUE TITLE
Can you update its not patched.

### ISSUE THREAD

**Issue by dustyroo** [Askwrite/node-csgo-reportbot#25]
Only patched for banned accounts

**Comment by LucasMartinsH** [comment]
+1

**Comment by Ar1i** [comment]
It's updated. But you can only report every 6h with unbanned CSGO Accounts.

**Comment by LucasMartinsH** [comment]
Hi Ar1i, it's not 6, its 12h.

**Comment by dream23** [comment]
i dont know how to install can someone help me plzz

**Comment by microscopicyt** [comment]
By "unbanned CSGO accounts" do you mean, non VAC banned accounts?

**Comment by TheRhanderson** [comment]
Yes
