### ISSUE TITLE
Reported myself to test it. It nothing happened.

### ISSUE THREAD

**Issue by 123top** [Askwrite/node-csgo-reportbot#28]
I only spinned 1 game and then reportbotted myself with 11 accounts (first time I used them) and after 21 hours I am still not banned. What have I done wrong? Any rules for reportbotting I missed or what? It can't be the colldown because I used them the first time for reports.

**Comment by EpicGreenMaster** [comment]
You need unbanned accounts

**Comment by 123top** [comment]
They are all unbanned. I think reportbot is broke maybe?

**Comment by TheRhanderson** [comment]
I tested Dr Pepper's ReportBot and AskWrite's ReportBot also.
All working, however, is relative. The cheater must have played two competitive in a row to have 99.9% chance to appear in Overwatch

**Comment by 123top** [comment]
I spinned 2 games. Still no ban after 30 hrs.

**Comment by TheRhanderson** [comment]
So you're doing something wrong.
I can ban people who have been offline for 18 hours and online too.

Rbotted list:
http://steamcommunity.com/profiles/76561198263022327/
http://steamcommunity.com/profiles/76561198338116765/
http://steamcommunity.com/profiles/76561198259272558/
http://steamcommunity.com/profiles/76561198159135070/
http://steamcommunity.com/profiles/76561197964746326/
http://steamcommunity.com/profiles/76561197965684213/
http://steamcommunity.com/profiles/76561198283251866/
http://steamcommunity.com/profiles/76561197965267632/
http://steamcommunity.com/profiles/76561197972326465/
http://steamcommunity.com/profiles/76561198343202718/
http://steamcommunity.com/profiles/76561198239918676/
http://steamcommunity.com/profiles/76561198332911446/
http://steamcommunity.com/profiles/76561198339951067/
http://steamcommunity.com/profiles/76561198337174694/
