### ISSUE TITLE
MatchID

### ISSUE THREAD

**Issue by Baterka** [Askwrite/node-csgo-reportbot#32]
Still trying to explain matchId field. Why default is 8?
Can i paste here real matchid decoded from gameid by "node-csgo" function?
I see in protos, that matchid field can be uint64.
Give this more chance to ban?

**Comment by TheRhanderson** [comment]
MatchID is no longer needed.
You can ban players who cheated in the last 20 hours easily.

**Comment by Baterka** [comment]
Yes i know but what mean the "8" and if i want use matchid, how?

**Comment by 123top** [comment]
Can you tell me how to get the matchID ? Pls for noobs? I don't know shit about coding.

**Comment by Askwrite** [comment]
U don't need it.
