### ISSUE TITLE
Protos or Bot.js Problem

### ISSUE THREAD

**Issue by Webisoft** [Askwrite/node-csgo-reportbot#33]
Few days ago it was working like a charm, but tried to reportbot some1 via classic method which is your script and its not working. After using script, entering steamid64 it does nothing, i used it coz i feel like reportbot web version by radat is getting me clean logs, but even with this i cant get any1 into OW.

So i dont know what could be reason script or protos or patch. Let me know.

Regards

**Comment by Askwrite** [comment]
Well, steam experienced yesterday some problems. (Fixing the gold profiles) That's may be the problem. Got some friends that reported some ragers aswell and they didn't get banned
