### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by elias5454** [Askwrite/node-csgo-reportbot#34]
C:\Users\ \Desktop\node>npm start

> csgo-reportbot@1.0.0 start C:\Users\ \Desktop\node
> node bot.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'steam'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ \Desktop\node\bot.js:2:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! csgo-reportbot@1.0.0 start: `node bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csgo-reportbot@1.0.0 start script 'node bot.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the csgo-reportbot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bot.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs csgo-reportbot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls csgo-reportbot
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ \Desktop\node\npm-debug.log

**Comment by Askwrite** [comment]
pls
