### ISSUE TITLE
Not a real problem but more a request...

### ISSUE THREAD

**Issue by INAX93** [Askwrite/node-csgo-reportbot#36]
Hi !
I'm unable to find a way to contact you...
I'm using your script to do commends, but i would like to be able to do it with accounts that got Steam Email Guard active... is there a way to do so ? i'm trying but i'm unable to make it work... :(
anyway thanks for your work ! and Happy New Year ! :)

**Comment by SiqSardines** [comment]
Just turn off steam guard lol that's what I did. Just make sure you have a decent password and you'll be fine. If anything does happen in which I doubt it will. You can always reset the password via your email.

**Comment by INAX93** [comment]
Actually turn off steam guard on more than 100 accounts isn't safe at all... And even with a strong password something can always happen... And u can't reset anything if the mail adress was changed before... That's why i'm doing this request...

**Comment by SiqSardines** [comment]
https://github.com/luk1337/vapor-report Use this. It has steam guard support and is based heavily off askwrite's bot.

**Comment by INAX93** [comment]
thanks for it but actually i need it in node.js... i'm trying to add the steam guard myself... but i'm pretty new to node.js tbh and but i guess i'll end to figure it out before i get any answer from Mr Askwrite... xD

**Comment by Askwrite** [comment]
I don't wanna be naughty or something like that, but if you are incapable to write/copy&paste few lines of code, I can't help you. There are lots of scripts where you can copy&paste and lots of docs about it.

**Comment by INAX93** [comment]
you see... that's the new generation of internet users... back in my time it was a pleasure to help others, especially those that were interested in any kind of our work or things we have done... it was ment to be shared... and today we get those kind of answers... "if you are incapable to write/copy&paste few lines of code, I can't help you" for a guy like you that obviously know well how to code in Node (maybe even code in general) this is as u tell, few mins of your time that u want even use to help/explain... i'm not a retard, maybe getting a ltl bit old but not retarded... it my first steps with Node and yes i felt on your script... i'm trying to make it work, i know that there is other based on other coding languages that actually already works, i reach to do trade bot with no real problems but based on "steam-user"... your code is based on "node-steam" and i'm unable to find any way to use "Session ID cookies" to use it with other modules (maybe its not the best way of doing it, but as i said, i'm rly new to Node, and my coding skills are limited to old languages, i'm working in systems and networks not as a dev... we can't know averything...) and in the node-steam docs, i can't find any way to use "sentry" files... so even if u use another code that i've made for tests that actually creates me a Sentry file... i'm still unable to use it...

anyway i'm used to get this kind of answers, since i started to try to learn node, all the answers are the same as urs... ppl don't have time, don't wanna help, don't wanna live chat to talk... can't spare 10 mins of their life to help...
i don't even mind paying for help/explanations, i'm willing to learn... but yep looks like i'm on my own like always :)

don't worry ammigo... i'm used to not getting help, it may takes me days, weeks, months... but if there is a way i'll find it... (maybe to late but still...).

Thanks anyway for the time that u took to at least answer me :) tbh i was waiting in hope that one of the "node" comunity guy would help xD now at least i know :)

Happy new year to you and u loved ones. and thank you for this script anyway ! :)

**Comment by Askwrite** [comment]
As I can see we're born in the same year (1993), so you don't have to talk about your "old time"... :)
So here's 1 method to do it:
1. Generate the sentryfile for each account and rename it to "accoutname.sentry". (Hopefully you can do this alone)
2. Create a dir called "sentryfiles" and copy all sentryfiles in it.
3.  Replace 
`SteamClients[indexElement].on("connected", function() {
            SteamUsers[indexElement].logOn({
                account_name: account_name,
                password: password
            });
        });` 
with 
`SteamClients[indexElement].on("connected", function() {
            SteamUsers[indexElement].logOn({
                account_name: account_name,
                password: password,
                sha_sentryfile: fs.readFileSync("sentryfiles/" + account_name + ".sentry")
            });
        });`
4. Done

I didn't test it, but it should work.

**Comment by INAX93** [comment]
lol i don't know where u found that but i'm not born in 93... i'm born the 01-01-87 actually (30years rn)... so for me it still "old times" lol...

But thanks a lot for that if there is a way to live chat with you (anyway) would be nice, cause i already tried this actually and this is what i get : 

```
              shaSentryfile: fs.readFileSync("sentryfiles/" + account_name + "
.sentry")
                ^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3


```
thanks again.

**Comment by INAX93** [comment]
i actually found that its "sha_sentryfile" now... but still doesn't work... i get error eresult: 63 login failed...

i'm trying i'm searching... but i can't get what is wrong... what is the problem... there is no explanation everywhere i'm searching... everything works easy and smooth with "steam-user" module... but with "node-steam" as long as u have steam guard everything is fucking complicated as hell (at least for me...)...

**Comment by Askwrite** [comment]
yea, my bad, it's sha_sentryfile.
https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd 
AccountLogonDenied = 63; your credentials/sentryfile are/is wrong.
Are you sure u saved the sentryfiles right?

**Comment by INAX93** [comment]
actually the sentry file i'm using is generated with "steam-user" it does it "auto"... as soon as u conect (after login password ans email code) it generate a sentry file called sentry.acc_name.bin... so i just used it renamed it in "acc_name.sentry" and tried like it... it looks like there is some kind of "options" to enable the use of sentry file... but as i said... i can't understand very well how all of this works... i used to code in Visual Basic like 15 years ago... so i have only the basics in coding ( and i'm not bad with web coding html5, css, javascript) ... but here i'm pretty much lost... all things i've understood is by reading and comparings scripts i find on web... but there are usualy old and based for most of them on old node-steam (0.6.8 for the most part)... and you are actually the first one that is trying to help... (i don't even know how to ask for help i usualy do all on my own...) :-/

so how can i know if the sentryfile is good ? it works good with steam-user it generates and call it himself without need of any code... :-/

**Comment by INAX93** [comment]
Ok actually i did it all back from scratch starting from node-steam... step by step... (and in this case here it was my sentry file that was not good... and even how i was sending it... sha_sentryfile takes actualy the sha1 of the updateMachineAuth that send the sentry datas event... :-/ ... but anyway everything works fine now and thanks one more time for your help !

i can finaly do all commendations smooth... juste a ltl optimisations to do to the code and will be cool... now moving on to the chat bot ! xD

take care amigo ! :)
