### ISSUE TITLE
Again...

### ISSUE THREAD

**Issue by aesto1** [Askwrite/node-csgo-reportbot#4]
I tried to do as you say and ....
C:\Users\Aesto>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path C:\Users\Aesto\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\Aesto\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Aesto\npm-debug.log

**Comment by Askwrite** [comment]
you have to download all the files, I think you forgot to download the packages.json file
